-- Generated by tusker

create sequence "public"."tick_id_seq";

create table "public"."tick" (
    "id" integer not null default nextval('tick_id_seq'::regclass)
);

alter table "public"."move_candidate" add column "tick_id" integer not null;

alter sequence "public"."tick_id_seq" owned by "public"."tick"."id";

CREATE UNIQUE INDEX tick_pkey ON public.tick USING btree (id);

alter table "public"."tick" add constraint "tick_pkey" PRIMARY KEY using index "tick_pkey";

alter table "public"."move_candidate" add constraint "move_candidate_tick_id_fkey" FOREIGN KEY (tick_id) REFERENCES tick(id) not valid;

alter table "public"."move_candidate" validate constraint "move_candidate_tick_id_fkey";

alter table "public"."tick" add column "time" timestamp with time zone not null default now();
