services:
  game:
    ports:
      - "8001:8001"
    environment:
      PORT: 8001

  smoke_test:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    environment:
      GAME_URL: http://game:8001
      DEBUG: $(DEBUG)
    profiles:
      - test
    volumes:
      - ./test:/app/test
      - ./src:/app/src
      - ./deno.jsonc:/app/deno.jsonc
      - ./import_map.json:/app/import_map.json
      - ./.env:/app/.env # Need all to comply with env schema
