name: citest

on:
  push:
    branches: [ citest ]
  workflow_dispatch:
    issue_comment:
      types: [created, edited]


jobs:
  citest:
    runs-on: ubuntu-latest
    steps:
      - run: echo citest2
